server:
    port: 21716

mybatis:
    type-aliases-package: com.cheney.satisfy.model
    mapper-locations: classpath:mapper/*.xml
    logImpl: STDOUT_LOGGING

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/satisfy
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

pagehelper:
        helperDialect: mysql
        reasonable: true
        supportMethodsArguments: true
        params: count=countSql

logging:
    level:
        org:
            mybatis: debug
        com:
            cheney:
                satisfy:
                    dao: debug

